version: "3.1"

services:
  interactive-video-web:
    build:
      dockerfile: Dockerfile
      context: ./interactive-video-web
    image: thalfm/interactive-video-web
    container_name: interactive-video-web
    volumes:
      - ./interactive-video-web/web:/opt/web
      - ./interactive-video-web/nginx/default:/etc/nginx/sites-available/default
    ports:
      - 8001:80
      - 3000:3000
    networks:
      - interactive-video

  interactive-video-api:
    build:
      dockerfile: Dockerfile
      context: ./interactive-video-api
      args:
        - WITH_XDEBUG=true
    image: thalfm/interactive-video-api
    container_name: interactive-video-api
    volumes:
      - ./interactive-video-api/api:/opt/api
      - ./interactive-video-api/nginx/default:/etc/nginx/sites-available/default
    ports:
      - 8000:80
    networks:
      - interactive-video
    env_file:
      - .env

  interactive-video-pgsql:
    image: postgres:13.1
    container_name: interactive-video-pgsql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=interactive
      - PGDATA=/temp/data
    volumes:
      - .database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - interactive-video
  interactive-video-rabbitmq:
    image: 'rabbitmq:3.8-management-alpine'
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - '.rabbitmq:/var/lib/rabbitmq/mnesia'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - interactive-video
networks:
  interactive-video:
    driver: bridge
