apiVersion: v1
kind: ConfigMap
metadata:
  name: interactive-video-web-nginx
data:
  default: |-
    server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /opt/web/build;
        index index.html;

        server_name _;

        access_log /var/log/nginx/interactive-video-web.access.log;
        error_log /var/log/nginx/interactive-video-web.error.log;

        location / {
            try_files $uri /index.html;
          }
    }