apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-customer-pvc-claim
  labels:
    app: rabbitmq-customer-pvc-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi