apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgsql-customer-pvc-claim
  labels:
    app: pgsql-customer-pvc-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi